/* Generated By:JJTree&JavaCC: Do not edit this line. CalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int SYMBOL = 5;
  /** RegularExpression Id. */
  int EQUAL = 6;
  /** RegularExpression Id. */
  int NEG = 7;
  /** RegularExpression Id. */
  int SC = 8;
  /** RegularExpression Id. */
  int LF = 9;
  /** RegularExpression Id. */
  int END = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "<INTEGER>",
    "<SYMBOL>",
    "\"=\"",
    "\"-\"",
    "\";\"",
    "\"\\r\"",
    "<END>",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
